{% set name = "altair-aitools-devkit" %}
{% set version = "1.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://maven.rapidminer.com/repository/pypi-snapshot/packages/altair-aitools-devkit/1.0b1/altair_aitools_devkit-1.0b1.tar.gz
  sha256: 3b3ee78cf6a41fa5c3ea9299a6415dd9f5aae2f238e8e2f0be7152dfc2618aa8

build:
  entry_points:
    - build-extension = altair_aitools.ext._builder:build_extension
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - numpy >=1.24.0,<2.0.0
    - packaging >=24.1.0,<25.0.0
    - pandas >=2.0.0,<3.0.0
    - pillow >=10.3.0,<11.0.0
    - pydantic >=2.0.0,<3.0.0
    - pyyaml >=6.0.0,<7.0.0
    - rapidminer >=2024.1.0,<2025.0.0
    - websockets >=12.0.0,<13.0.0
  run_constrained:
    - typing_extensions >=4.12.2,<5.0.0

test:
  imports:
    - altair_aitools
  commands:
    - pip check
    - build-extension --help
  requires:
    - pip

about:
  summary: altair-aitools-devkit is a comprehensive package that provides a set of tools to develop Altair RapidMiner AI tools extensions in Python
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - somakontar
